apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
spec:
  metrics:
  - name: success-rate
    successCondition: result[0] >= 0.95
    failureLimit: 1
    provider:
      prometheus:
        address: "http://prometheus.istio-system:9090"
        query: |
           sum(irate(istio_requests_total{reporter="source",destination_service=~"rollouts-demo-canary.rollout-demo.svc.cluster.local",response_code!~"5.*"}[5s])) /
           sum(irate(istio_requests_total{reporter="source",destination_service=~"rollouts-demo-canary.rollout-demo.svc.cluster.local"}[5s]))
